---
- hosts: webservers
  become: yes
  tasks: 
  - name: intall git 1
    yum:
      namee: git
      state: present
    ignore_errors: yes
    
    
  - name: intall tree 2
    yum:
      name: tree
      state: present
    

  - name: intall wget 3
    yum:
      name: wget
      state: present
      