---
- hosts: webservers
  become: yes
  tasks: 
  - name: intall git 1
    yum:
      name: git
      state: present
    
    
  - name: intall tree 2
    yum:
      namee: tree
      state: present
    ignore_errors: yes

  - name: intall wget 3
    yum:
      name: wget
      state: present
      