---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: intall webserver on redhat
    yum:
      name: httpd
      state: present
      notify: restartwebserver

  - name: copy index file 
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: restartwebserver
    
  - name: service start
    service:
      name: httpd
      state: restarted