---
- hosts: all
  become: yes
  tasks: 
  - name: des install git, tree and wget on ubuntu
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - tree
      - wget